# Generated by Django 2.2.3 on 2019-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('headline', models.CharField(blank=True, max_length=150)),
                ('biography', models.CharField(blank=True, max_length=500)),
                ('lg', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
